set(_CATKIN_CURRENT_PACKAGE "youbot_manual_operation")
set(youbot_manual_operation_VERSION "0.0.0")
set(youbot_manual_operation_MAINTAINER "robert <valnerrobert@gmail.com>")
set(youbot_manual_operation_PACKAGE_FORMAT "1")
set(youbot_manual_operation_BUILD_DEPENDS "roscpp" "std_msgs" "message_generation" "joy")
set(youbot_manual_operation_BUILD_EXPORT_DEPENDS "roscpp" "joy" "std_msgs" "message_runtime")
set(youbot_manual_operation_BUILDTOOL_DEPENDS "catkin")
set(youbot_manual_operation_BUILDTOOL_EXPORT_DEPENDS )
set(youbot_manual_operation_EXEC_DEPENDS "roscpp" "joy" "std_msgs" "message_runtime")
set(youbot_manual_operation_RUN_DEPENDS "roscpp" "joy" "std_msgs" "message_runtime")
set(youbot_manual_operation_TEST_DEPENDS )
set(youbot_manual_operation_DOC_DEPENDS )
set(youbot_manual_operation_URL_WEBSITE "")
set(youbot_manual_operation_URL_BUGTRACKER "")
set(youbot_manual_operation_URL_REPOSITORY "")
set(youbot_manual_operation_DEPRECATED "")