# CMake generated Testfile for 
# Source directory: /home/lucas/catkin_ws/src/youbot/youbot_manipulation/youbot_arm_kinematics_moveit
# Build directory: /home/lucas/catkin_ws/src/youbot/youbot_manipulation/youbot_arm_kinematics_moveit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_youbot_arm_kinematics_moveit_gtest_load_moveit_plugin_test "/home/lucas/catkin_ws/src/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/lucas/catkin_ws/src/test_results/youbot_arm_kinematics_moveit/gtest-load_moveit_plugin_test.xml" "--return-code" "/home/lucas/catkin_ws/devel/lib/youbot_arm_kinematics_moveit/load_moveit_plugin_test --gtest_output=xml:/home/lucas/catkin_ws/src/test_results/youbot_arm_kinematics_moveit/gtest-load_moveit_plugin_test.xml")
set_tests_properties(_ctest_youbot_arm_kinematics_moveit_gtest_load_moveit_plugin_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/lucas/catkin_ws/src/youbot/youbot_manipulation/youbot_arm_kinematics_moveit/CMakeLists.txt;41;catkin_add_gtest;/home/lucas/catkin_ws/src/youbot/youbot_manipulation/youbot_arm_kinematics_moveit/CMakeLists.txt;0;")
add_test(_ctest_youbot_arm_kinematics_moveit_gtest_youbot_arm_kinematics_moveit_test "/home/lucas/catkin_ws/src/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/lucas/catkin_ws/src/test_results/youbot_arm_kinematics_moveit/gtest-youbot_arm_kinematics_moveit_test.xml" "--return-code" "/home/lucas/catkin_ws/devel/lib/youbot_arm_kinematics_moveit/youbot_arm_kinematics_moveit_test --gtest_output=xml:/home/lucas/catkin_ws/src/test_results/youbot_arm_kinematics_moveit/gtest-youbot_arm_kinematics_moveit_test.xml")
set_tests_properties(_ctest_youbot_arm_kinematics_moveit_gtest_youbot_arm_kinematics_moveit_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/lucas/catkin_ws/src/youbot/youbot_manipulation/youbot_arm_kinematics_moveit/CMakeLists.txt;49;catkin_add_gtest;/home/lucas/catkin_ws/src/youbot/youbot_manipulation/youbot_arm_kinematics_moveit/CMakeLists.txt;0;")
add_test(_ctest_youbot_arm_kinematics_moveit_gtest_configuration_comparator_test "/home/lucas/catkin_ws/src/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/lucas/catkin_ws/src/test_results/youbot_arm_kinematics_moveit/gtest-configuration_comparator_test.xml" "--return-code" "/home/lucas/catkin_ws/devel/lib/youbot_arm_kinematics_moveit/configuration_comparator_test --gtest_output=xml:/home/lucas/catkin_ws/src/test_results/youbot_arm_kinematics_moveit/gtest-configuration_comparator_test.xml")
set_tests_properties(_ctest_youbot_arm_kinematics_moveit_gtest_configuration_comparator_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/lucas/catkin_ws/src/youbot/youbot_manipulation/youbot_arm_kinematics_moveit/CMakeLists.txt;57;catkin_add_gtest;/home/lucas/catkin_ws/src/youbot/youbot_manipulation/youbot_arm_kinematics_moveit/CMakeLists.txt;0;")
